name: Matrix Workflow

on: [push]

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2, 3]
    steps:
      - run: echo "Running version ${{ matrix.version }}"
