name: Needs Optimization
on: [push]

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

  job-b:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

  job-c:
    runs-on: ubuntu-latest
    needs: job-a  
    steps:
      - run: echo "Job C waits but doesn't depend on the job"

  test-integration:
    if: ${{ false }}  # always skipped
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip"

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build run"
